name = "aisex"
main = "worker.js"
compatibility_date = "2026-01-29"
keep_vars = true

# [重要] 开启 Node.js 兼容模式
compatibility_flags = ["nodejs_compat"]

# 部署按钮会自动覆盖这里的配置，或者提示用户创建
[[d1_databases]]
binding = "DB"
database_name = "aisex"
database_id = "7aa630e0-7baa-419c-bf17-962eeb825a9a"
